import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}

// // ##
// import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
// import "./globals.css";
// import ThemeToggle from "@/components/general/ThemeToggle";

// const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] });

// export const metadata: Metadata = {
//   title: "My Portfolio",
//   description: "A personal portfolio built with Next.js and Prisma",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.className} dark`}>
//         <header className="gradient-bg text-white p-4 sticky top-0 z-50">
//           <div className="container mx-auto flex justify-between items-center">
//             <a href="/" className="text-2xl font-bold">
//               Portfolio
//             </a>
//             <nav className="flex items-center space-x-4">
//               <a href="/dashboard" className="hover:underline">
//                 Dashboard
//               </a>
//               <a href="/projects" className="hover:underline">
//                 Projects
//               </a>
//               <a href="/about" className="hover:underline">
//                 About
//               </a>
//               <a href="/admin" className="hover:underline">
//                 Admin
//               </a>
//               <ThemeToggle />
//             </nav>
//           </div>
//         </header>
//         {children}
//       </body>
//     </html>
//   );
// }
